## if demo1
  deploy:
    runs-on: ubuntu-latest
    needs: linux
    steps:
    - if: github.event_name == 'release' && github.event.action == 'created'
      uses: actions/checkout@v1
    - if: github.event_name == 'release' && github.event.action == 'created'
      name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - if: github.event_name == 'release' && github.event.action == 'created'
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - if: github.event_name == 'release' && github.event.action == 'created'
      name: Build and deploy to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*


# if demo2 https://docs.github.com/cn/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      ...
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      ...

## if demo3 if通知
    # Notify to slack when test failed
    - name: Slack test failure notification
      if: failure()
      run: |
        curl -X POST --data-urlencode 'payload={
          "text": ":fire::fire::fire:${{github.repository}}: Test failed..:fire::fire::fire:"
        }' ${{secrets.SLACK_WEBHOOK_URL}}
    # Notify to slack when build and test succeeded
    - name: Slack success notification
      if: success()
      run: |
        curl -X POST --data-urlencode 'payload={
          "text": ":tada::tada::tada:${{github.repository}}: Build and Test succeeded！:tada::tada::tada:"
        }' ${{secrets.SLACK_WEBHOOK_URL}}
