#https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows
#https://docs.github.com/cn/actions/learn-github-actions/workflow-commands-for-github-actions
on: [push, pull_request]
name: build
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
      - name: Test with input
        uses: actions/hello-world-docker-action@master
        with:
          who-to-greet: Mona-the-Octocat-${{ steps.date.outputs.date }}



#demo2

      - name: Dump GitHub context
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
        #run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Get Env
        run: echo '${{ env.RELEASE_VERSION }}'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ env.RELEASE_VERSION }}

#demo3
      - name: Dump GitHub context
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

#https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#environment-files
echo "{name}={value}" >> $GITHUB_ENV


#全局env

env:
  ACTOR: Myki

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Settings env
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          skopeo --version
          echo '${{ env.NOW }}'
          echo '${{ env.ACTOR }}'



#echo ::set-env name=IMAGE_TAG::${IMAGE_TAG}


- name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
